import Head from "next/head";
import { Link } from "@mui/material";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Paraffin</h1>
        <h1 className={styles.title}>by V3N1</h1>
        <p className={styles.description}>
          Discover your next career as a software developer
        </p>

        <div className={styles.grid}>
          <Link href="/users/sign_up" className={styles.card}>
            <h2>Sign up &rarr;</h2>
            <p>
              You couldn&apos;t have found a better place to start your career.
            </p>
          </Link>

          <Link href="/users/sign_in" className={styles.card}>
            <h2>Log in &rarr;</h2>
            <p>Already have an account? Continue your learning journey here.</p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://fin.fintual.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with ❤️ in Patagonia
        </a>
      </footer>
    </div>
  );
}
